export const myConfig = { 
    // hostName:'http://127.0.0.1:8000',
    hostName:'https://social-net-216.herokuapp.com',
    mediaHost:'',
    // mediaHost:'http://127.0.0.1:8000',
    // socketHostName:'ws://127.0.0.1:8000',
    socketHostName:'wss://social-net-216.herokuapp.com',
    defaultAvatar: 'https://social-net-188.herokuapp.com/default_avatar.jpg',
    defaultHashtag: 'https://social-net-188.herokuapp.com/default_hashtag.png',
    getError: 'Cannot get data from server.',
    sendError: 'Cannot send data to server.',
    serverError: 'Cannot connect to server.',
    settingSaved: 'Setting saved.',
    deletedPost: 'Post deleted.',
    editedPost: 'Post edited.',
    sent: 'Sent.',
}